# Generated by Django 3.2.18 on 2023-05-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
