# Generated by Django 3.2.18 on 2023-05-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_kakao_user',
            field=models.BooleanField(default=False),
        ),
    ]
