# Generated by Django 3.2.18 on 2023-05-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_kakao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_kakao_user',
        ),
    ]
