# Generated by Django 3.2.18 on 2023-05-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_kakao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_confirm',
        ),
    ]
