# Generated by Django 3.2.18 on 2023-05-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
